# Generated by Django 2.0.6 on 2018-10-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterwaveApp', '0002_auto_20181010_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterwave',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
